### ISSUE TITLE
Crash Game

### ISSUE THREAD

**Issue by QueenUlyana** [IMB11/xanders-sodium-options#16]
@isXander When you try to open the "graphics settings", the game closes.
https://gist.github.com/QueenUlyana/9e3d46efefc8de9e1d83c9bd41c974d5

**Comment by ruvaldak** [comment]
this is due to an update to YACL, the config library this mod depends on. Downgrade to YACL 2.5.1 for now.

**Comment by HhiPyrene** [comment]
Crashed too.
Also, seems all the config screens using YACL cannot work caused by the new version of YACL.
```
Description: mouseClicked event handler

java.lang.NoSuchMethodError: 'dev.isxander.yacl.api.Option$Builder dev.isxander.yacl.api.Option$Builder.tooltip(net.minecraft.class_2561[])'
	at dev.isxander.xso.XandersSodiumOptions.convertOption(XandersSodiumOptions.java:114)
	at dev.isxander.xso.XandersSodiumOptions.convertCategory(XandersSodiumOptions.java:86)
	at dev.isxander.xso.XandersSodiumOptions.wrapSodiumScreen(XandersSodiumOptions.java:39)
	at net.minecraft.class_310.localvar$clf000$xanders-sodium-options$modifyScreen(class_310.java:15995)
	at net.minecraft.class_310.method_1507(class_310.java)
	at net.minecraft.class_429.method_47624(class_429.java:153)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:57)
	at net.minecraft.class_339.method_25402(class_339.java:187)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:540)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:198)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:209)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1238)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
```

**Comment by QueenUlyana** [comment]
> this is due to an update to YACL, the config library this mod depends on. Downgrade to YACL 2.5.1 for now.

I have "yet-another-config-lib-fabric-3.0.0-beta.1+1.19.4.jar", or is it needed exactly 2.5.1? Forgot to clarify, I play on version 1.19.4. The last update for Xander's Sodium Options was on 1.19.3. I think the problem may be this, the lack of a version for 1.19.4
